[package]
name = "hoon"
version = "0.0.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Hoon language parser"
repository = "https://github.com/rsaarelm/hoon-rs"
license = "MIT OR Apache-2.0"

[dependencies]
nock = "0.2.1"
fnv = "1.0"
time = "0.1"
num = "0.1"
bit-vec = "0.4"
