[package]
name = "urbit"
version = "0.0.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Urbit utilities"
repository = "https://github.com/rsaarelm/urbit-rs"
license = "MIT"

[dependencies]
nock = "0.2"
num = "*"
bit-vec = "*"

[[example]]
name = "urbit"
path = "examples/urbit.rs"
