[package]
name = "urbit"
version = "0.0.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Urbit utilities"
repository = "https://github.com/rsaarelm/urbit-rs"
license = "MIT"

[dependencies]
nock = { git = "https://github.com/rsaarelm/nock-rs" }
num = "*"
bit-vec = "*"
